"""Configuration module for Samantha."""

from .constants import (
    SAMPLE_RATE,
    WHISPER_SAMPLE_RATE,
    CHANNELS,
    WHISPER_URL,
    KOKORO_URL,
    SAMANTHA_DIR,
    CONFIG_FILE,
    SAMANTHA_ACTIVE_FILE,
    CONVERSATION_LOG,
    LOG_FILE,
    LOG_LEVEL,
    DEFAULT_WAKE_WORDS,
    STOP_PHRASES,
    DEFAULT_DEACTIVATION_PHRASES,
    INTERRUPT_WORDS,
    SKIP_WORDS,
    WHISPER_SOUND_PATTERN,
    SUPPORTED_IDES,
    IDE_PROCESS_NAMES,
    SUPPORTED_TERMINALS,
    SUPPORTED_APPS,
)

from .settings import (
    load_config,
    get_config,
    get_voice,
    get_input_device,
    get_output_device,
    get_show_status,
    get_restore_focus,
    get_theodore_mode,
    get_min_audio_energy,
    get_wake_words,
    get_deactivation_phrases,
)

__all__ = [
    # Constants
    "SAMPLE_RATE",
    "WHISPER_SAMPLE_RATE",
    "CHANNELS",
    "WHISPER_URL",
    "KOKORO_URL",
    "SAMANTHA_DIR",
    "CONFIG_FILE",
    "SAMANTHA_ACTIVE_FILE",
    "CONVERSATION_LOG",
    "LOG_FILE",
    "LOG_LEVEL",
    "DEFAULT_WAKE_WORDS",
    "STOP_PHRASES",
    "DEFAULT_DEACTIVATION_PHRASES",
    "INTERRUPT_WORDS",
    "SKIP_WORDS",
    "WHISPER_SOUND_PATTERN",
    "SUPPORTED_IDES",
    "IDE_PROCESS_NAMES",
    "SUPPORTED_TERMINALS",
    "SUPPORTED_APPS",
    # Settings
    "load_config",
    "get_config",
    "get_voice",
    "get_input_device",
    "get_output_device",
    "get_show_status",
    "get_restore_focus",
    "get_theodore_mode",
    "get_min_audio_energy",
    "get_wake_words",
    "get_deactivation_phrases",
]
