"""Configuration module for Samantha."""

from .constants import (
    SAMPLE_RATE,
    WHISPER_SAMPLE_RATE,
    CHANNELS,
    WHISPER_URL,
    KOKORO_URL,
    SAMANTHA_DIR,
    CONFIG_FILE,
    SAMANTHA_ACTIVE_FILE,
    CONVERSATION_LOG,
    LOG_FILE,
    LOG_LEVEL,
    DEFAULT_WAKE_WORDS,
    STOP_PHRASES,
    DEFAULT_DEACTIVATION_PHRASES,
    INTERRUPT_WORDS,
    SKIP_WORDS,
    VOICE_MESSAGE_PREFIX,
    WHISPER_SOUND_PATTERN,
    SUPPORTED_IDES,
    IDE_PROCESS_NAMES,
    SUPPORTED_TERMINALS,
    DESKTOP_APP_NAMES,
    SUPPORTED_DESKTOP_APPS,
    SUPPORTED_APPS,
    DEFAULT_AI_PROCESS_PATTERN,
    DEFAULT_AI_WINDOW_TITLES,
)

from .profiles import PROFILES, DEFAULT_PROFILE

from .settings import (
    load_config,
    get_config,
    get_profile_name,
    get_profile,
    get_voice,
    get_input_device,
    get_output_device,
    get_restore_focus,
    get_theodore_mode,
    get_user_name,
    get_min_audio_energy,
    get_wake_words,
    get_stop_phrases,
    get_deactivation_phrases,
    get_target_app,
    get_injection_mode,
    get_ai_process_pattern,
    get_ai_window_titles,
)

__all__ = [
    # Constants
    "SAMPLE_RATE",
    "WHISPER_SAMPLE_RATE",
    "CHANNELS",
    "WHISPER_URL",
    "KOKORO_URL",
    "SAMANTHA_DIR",
    "CONFIG_FILE",
    "SAMANTHA_ACTIVE_FILE",
    "CONVERSATION_LOG",
    "LOG_FILE",
    "LOG_LEVEL",
    "DEFAULT_WAKE_WORDS",
    "STOP_PHRASES",
    "DEFAULT_DEACTIVATION_PHRASES",
    "INTERRUPT_WORDS",
    "SKIP_WORDS",
    "VOICE_MESSAGE_PREFIX",
    "WHISPER_SOUND_PATTERN",
    "SUPPORTED_IDES",
    "IDE_PROCESS_NAMES",
    "SUPPORTED_TERMINALS",
    "DESKTOP_APP_NAMES",
    "SUPPORTED_DESKTOP_APPS",
    "SUPPORTED_APPS",
    "DEFAULT_AI_PROCESS_PATTERN",
    "DEFAULT_AI_WINDOW_TITLES",
    # Profiles
    "PROFILES",
    "DEFAULT_PROFILE",
    # Settings
    "load_config",
    "get_config",
    "get_profile_name",
    "get_profile",
    "get_voice",
    "get_input_device",
    "get_output_device",
    "get_restore_focus",
    "get_theodore_mode",
    "get_user_name",
    "get_min_audio_energy",
    "get_wake_words",
    "get_stop_phrases",
    "get_deactivation_phrases",
    "get_target_app",
    "get_injection_mode",
    "get_ai_process_pattern",
    "get_ai_window_titles",
]
